apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-h5of
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-h5of
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-h5of
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-h5of
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-h5of
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ugvo-tenant/rhtap-demo-app/hacbs-test-project-h5of@sha256:64459264e00845c7f6fa096312ae73160fbe0355ec15b3815b084238b2713d1f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
