apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-h5of
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ugvo-tenant/rhtap-demo-app/hacbs-test-project-h5of@sha256:64459264e00845c7f6fa096312ae73160fbe0355ec15b3815b084238b2713d1f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
